version: "3"

services:
  mydb:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=app
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
